### ISSUE TITLE
Pianochords.io now available via Raycast too

### ISSUE THREAD

**Issue by juhamust** [JNKKKK/pianochord.io#3]
I adapted project's codebase into [Raycast](https://www.raycast.com/) extension: https://www.raycast.com/juhamust/pianoman

While the extension is a standalone solution, it contains links back to the pianochords.io service:

![image](https://user-images.githubusercontent.com/781002/194124982-a0d951e8-def2-4ee5-b6fa-701a3d1a0869.png)

Thus, thank you for sharing the project with a liberal license, which makes these derivative works possible.

**Comment by juhamust** [comment]
Oh, only now I notice the typo in the name 🙈 Will fix it in the next release. The link works, though.

**Comment by JNKKKK** [comment]
That's awesome!!!
